### ISSUE TITLE
Error parsing addr: [0, 0, 0, 0]

### ISSUE THREAD

**Issue by mhanne** [mhanne/bitcoin-ruby-node#2]
Sometimes this happens. Not a big deal but should be fixed.

```
DEBUG network: 128.8.124.7:8333 >> addr: 128.8.124.7:8333 alive: true, service: 1
Error parsing addr: [0, 0, 0, 0]
 WARN network: 128.8.124.7:8333 Error handling data: f9beb4d961646472000000000000000023000000278490750170c85055010000000000000000000000000000000000ffff80087c07208d00000000
#<NoMethodError: undefined method `ip' for nil:NilClass>
/home/webbtc/bitcoin-ruby-node/lib/bitcoin/node/connection_handler.rb:159:in `block in on_addr'
/home/webbtc/.bundler/ruby/2.1.0/bitcoin-ruby-664b63a369c3/lib/bitcoin/logger.rb:61:in `call'
/home/webbtc/.bundler/ruby/2.1.0/bitcoin-ruby-664b63a369c3/lib/bitcoin/logger.rb:61:in `block in method_missing'
(eval):5:in `debug'
/home/webbtc/.bundler/ruby/2.1.0/bitcoin-ruby-664b63a369c3/lib/bitcoin/logger.rb:61:in `method_missing'
/home/webbtc/bitcoin-ruby-node/lib/bitcoin/node/connection_handler.rb:159:in `on_addr'
/home/webbtc/.bundler/ruby/2.1.0/bitcoin-ruby-664b63a369c3/lib/bitcoin/protocol/parser.rb:55:in `block in parse_addr'
/home/webbtc/.bundler/ruby/2.1.0/bitcoin-ruby-664b63a369c3/lib/bitcoin/protocol/parser.rb:49:in `each_slice'
/home/webbtc/.bundler/ruby/2.1.0/bitcoin-ruby-664b63a369c3/lib/bitcoin/protocol/parser.rb:49:in `parse_addr'
/home/webbtc/.bundler/ruby/2.1.0/bitcoin-ruby-664b63a369c3/lib/bitcoin/protocol/parser.rb:86:in `process_pkt'
/home/webbtc/.bundler/ruby/2.1.0/bitcoin-ruby-664b63a369c3/lib/bitcoin/protocol/parser.rb:163:in `parse_buffer'
/home/webbtc/.bundler/ruby/2.1.0/bitcoin-ruby-664b63a369c3/lib/bitcoin/protocol/parser.rb:135:in `parse'
/home/webbtc/bitcoin-ruby-node/lib/bitcoin/node/connection_handler.rb:65:in `block in receive_data'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/webbtc/bitcoin-ruby-node/lib/bitcoin/node/connection_handler.rb:65:in `receive_data'
/var/lib/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
/var/lib/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
/home/webbtc/bitcoin-ruby-node/lib/bitcoin/node.rb:237:in `run'
bin/bitcoin_node:159:in `<main>'
```

**Comment by mhanne** [comment]
fixed d9a532a
