### ISSUE TITLE
Could not find a valid gem 'bitcoin-ruby-node' (>= 0) in any repository

### ISSUE THREAD

**Issue by igorbarinov** [mhanne/bitcoin-ruby-node#4]
Here is error log

> ubuntu@ip-172-31-36-36:~$ gem install bitcoin-ruby-node
> ERROR:  Could not find a valid gem 'bitcoin-ruby-node' (>= 0) in any repository
> ERROR:  Possible alternatives: bitcoin-ruby, bitcoin_node, bitcoin_payable, bitcoinde, bitcointoyou

How to install it?

**Comment by igorbarinov** [comment]
Found gem install bitcoin_node. Is it right one?

it gives me 
[2015-06-04T21:00:01.940300 #25990]  INFO -- NODE: Parsing inv
/home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/protocol.rb:182:in `inspect': inspected result must be ASCII only or use the default external encoding (Encoding::CompatibilityError)
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/protocol.rb:182:in`to_s'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:98:in `p'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:98:in`parse'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:53:in `parse'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:32:in`block in send'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:28:in `loop'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:28:in`send'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:82:in `block in parse'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:56:in`call'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:56:in `parse'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:32:in`block in send'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:28:in `loop'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/lib/bitcoin_node/p2p/client.rb:28:in`send'
    from /home/ubuntu/.rvm/gems/ruby-head/gems/bitcoin_node-0.0.2/bin/bitcoin_node:13:in `block (2 levels) in <top (required)>'

**Comment by igorbarinov** [comment]
I used ruby 2.1 and it caused this error.
after switching to 1.9.3 the error disappear

**Comment by mhanne** [comment]
Hi, I'm sorry but there isn't a gem for the bitcoin node yet. It needs some patches from my git repo that aren't in bitcoin-ruby upstream, and I couldn't figure out how to write a gemspec for that. Please just clone the repo and run bundler for now... Getting this sorted out is on my todo list, but not with the highest of priorities - tell me if it would be important to you.

 The `bitcoin_node` gem is something different: https://github.com/simcap/bitcoin_node

**Comment by patha046** [comment]
Hi @mhanne, I am working on a project on blockchain and it would be very helpful if this issue is sorted.

**Comment by SIKOo971** [comment]
bro is there any solution to install your blockexplorer with bitcored
