### ISSUE TITLE
Undefined method `alive?' for nil:NilClass

### ISSUE THREAD

**Issue by chinh7** [mhanne/bitcoin-ruby-node#5]
I see this sometimes in the log. Is it something to be concerned about? Thanks

``` bash
Error parsing addr: [0, 0, 0, 0]
INFO  network: requesting addrs
#<NoMethodError: undefined method `alive?' for nil:NilClass>
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/bitcoin-ruby-node-29605f8454b5/lib/bitcoin/node/command_handler.rb:287:in `block in handle_info'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/bitcoin-ruby-node-29605f8454b5/lib/bitcoin/node/command_handler.rb:287:in `select'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/bitcoin-ruby-node-29605f8454b5/lib/bitcoin/node/command_handler.rb:287:in `handle_info'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/bitcoin-ruby-node-29605f8454b5/lib/bitcoin/node/command_handler.rb:47:in `block in receive_data'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/bitcoin-ruby-node-29605f8454b5/lib/bitcoin/node/command_handler.rb:33:in `each'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/bitcoin-ruby-node-29605f8454b5/lib/bitcoin/node/command_handler.rb:33:in `receive_data'
/usr/local/rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
/usr/local/rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/bitcoin-ruby-node-29605f8454b5/lib/bitcoin/node.rb:237:in `run'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/bitcoin-ruby-node-29605f8454b5/bin/bitcoin_node:159:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/bitcoin_node:23:in `load'
/usr/local/rvm/gems/ruby-2.1.5/bin/bitcoin_node:23:in `<main>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mhanne** [comment]
Hi, thanks for bringing it up!
This is not a big problem, it just means that it couldn't parse some peer address it received.
I was hoping https://github.com/lian/bitcoin-ruby/pull/159 would make it into upstream, but I have merged it onto my "next" branch now so we can use the fix.

You might have to `bundle update bitcoin-ruby` explicitly, after you update bitcoin-ruby-node.
